ALTER TABLE investments ADD COLUMN market TEXT NOT NULL DEFAULT 'TW';
ALTER TABLE investments ADD COLUMN broker TEXT NOT NULL DEFAULT '';
ALTER TABLE investments ADD COLUMN order_channel TEXT NOT NULL DEFAULT '';
ALTER TABLE investments ADD COLUMN trade_currency TEXT NOT NULL DEFAULT 'TWD';
ALTER TABLE investments ADD COLUMN settlement_currency TEXT NOT NULL DEFAULT 'TWD';
ALTER TABLE investments ADD COLUMN fx_rate_to_twd REAL NOT NULL DEFAULT 1;
ALTER TABLE investments ADD COLUMN fee_amount REAL NOT NULL DEFAULT 0;
ALTER TABLE investments ADD COLUMN fee_currency TEXT NOT NULL DEFAULT 'TWD';
ALTER TABLE investments ADD COLUMN net_amount_twd REAL NOT NULL DEFAULT 0;

ALTER TABLE prices ADD COLUMN market TEXT NOT NULL DEFAULT 'TW';
ALTER TABLE prices ADD COLUMN currency TEXT NOT NULL DEFAULT 'TWD';
ALTER TABLE prices ADD COLUMN fx_rate_to_twd REAL NOT NULL DEFAULT 1;
